server:
  port: 18082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: anta.2345
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 50000
      max-lifetime: 54000
      connection-timeout: 60000
      auto-commit: true
      connection-test-query: SELECT 1
  activiti:
    check-process-definitions: false
    database-schema-update: true
  redis:
    host: 127.0.0.1
    port: 6379


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hrabbit.admin.modual.system.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

thymeleaf:
  mode: LEGACYHTML5
  cache: false

security:
  basic:
    enabled: false

logging:
  config: classpath:logback-boot.xml
