server:
  port: 18082

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: anta.2345
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 50000
      max-lifetime: 54000
      connection-timeout: 60000
      auto-commit: true
      connection-test-query: SELECT 1
  activiti:
    check-process-definitions: false
    database-schema-update: true
    async-executor-activate: false
  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: abc.54321
#    client-type: lettuce
#    timeout: 60000
    redisson:
      file: classpath:redisson.yaml
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: /
    username: guest
    password: guest

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://abc.54321@localhost:6379/11
      password: abc.54321


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hrabbit.admin.modual.system.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    table-underline: true
    map-underscore-to-camel-case: false

thymeleaf:
  mode: LEGACYHTML5
  cache: false

security:
  basic:
    enabled: false

logging:
  config: classpath:logback-boot.xml
